### ISSUE TITLE
Update tables for mobile screens

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#131]
- Update tables to fit the mobile screen (instead of scrollable tables)

**Comment by Jereriviel** [comment]
Tables have been updated, creating overlays with information is left.

**Comment by Jereriviel** [comment]
We decided to put information icons to the left on each row in the mobile tables and I prototyped navigating to a new page when clicking on the rows, and Martine has created information overlays which she will prototype to pop up when clicking on the information icons.

**Comment by Martinekong** [comment]
I have now added the prototyping for all the table overlays so that they open when the user clicks the "info" icon. I also prototyped it so that when the user clicks delete, the overlay switches to the "are you sure"-overlays that Carina had already created. 
The new overlays have been added to the style guide.

**Comment by pauiws** [comment]
Review completed.
