### ISSUE TITLE
Adjust body texts to left aligned and add more padding

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#140]
## Tasks
- Change body texts on Landing page, About page and Contact page to be left aligned
- Add some more side padding to the texts so they become more like a box and don't take up the whole width of the page

![Image](https://github.com/user-attachments/assets/7df4381d-cd19-4c80-8ef2-e42bcd50b83e)

<br>

- [x] Desktop
- [x] Mobile

**Comment by Anne-Zwift** [comment]
@Mayamariaruth @kristinatonnessen just a quick question: I see some closed eyes on the Figma landing page. When I open them, the elements start to move and the page looks like a mess. Should I leave them closed and just continue doing my task, or should I try to fix the site?

**Comment by kristinatonnessen** [comment]
@Anne-Zwift @Mayamariaruth I saw that some elements were hidden, but I don't know why, I think I saw that someone from mayas group did it to clean up before the presentation, wait to see what she answers🤔

**Comment by Mayamariaruth** [comment]
I asked my team, I'll get back to you

**Comment by Mayamariaruth** [comment]
@Anne-Zwift @kristinatonnessen my team thought they had deleted these while creating the auto-layout but they missed these elements, they’ll delete them!

**Comment by Anne-Zwift** [comment]
Desktop:
- Landing Page desktop: added padding 40px w+h to the Frame 50. Body text to the left.
- About: (the body text is size 20, and line height auto. I have not changed it but left a comment in Figma).  added padding 40px w+h to the Frame 50. Body text to the left.
- Contact: added padding 40px w+h to the Frame 50. Body text to the left.

Mobile:
To make everything match I have:
- Landing page: Body text align to left. 
- About: New padding size 40 to the Main, Body text align to left.
- Contact: New padding size 40 to the Main, Body text align to left.
- Contact - On Error: Body text align to left. Did not change the padding due to the error message. Text box size to W320px and 90H.

@kristinatonnessen @Mayamariaruth @Janicke92 this is now put to review.

**Comment by Janicke92** [comment]
The padding looks good on all pages. 
The text is aligned left on About page and Contact page on mobile and desktop. 

I can see that the text is aligned left on the landing page for mobile and desktop, but it looks centered to my eye. Asking @Mayamariaruth  for clarification if the text needs to be changed more. 

Text aligned left is missing from Contact - On Error page on desktop.

**Comment by Anne-Zwift** [comment]
@Janicke92 I've adjusted Contact page - On Error page on desktop. Text aligned to left.

**Comment by Janicke92** [comment]
Great! Still waiting on clarification on the landing page. @Mayamariaruth

**Comment by Mayamariaruth** [comment]
I think the landing page text looks good like that but we might have to update it after fixing the hero image to fit the full page
