### ISSUE TITLE
Make components

### ISSUE THREAD

**Issue by AilinMari** [NoroffFEU/edu-gate#69]
Make components outof the things that is repetative

- [x] #93 desktop
- [x] #94

<br>

### Tables
- [x] #63 

<br>

### Form fields
- [x] #102 
- [x] Regular form fields

**Comment by Jereriviel** [comment]
Hi, just a little heads up that I will be making components for the tables in both desktop and mobile :)

See issue: https://github.com/NoroffFEU/edu-gate/issues/63

**Comment by AilinMari** [comment]
I see. It's a lot of details in one ticket, thats not optimal, and it's easy to miss. Also hard for others to pick up tasks when they are all in one ticket. I have been talkin with our SM about the issue, he will talk with the rest of the SM's :) Meanwhile you can pick up this ticket if you like! :)

**Comment by Jereriviel** [comment]
@AilinMari I would say that normally the components would have been created underway in the styling process, but it doesn't seem to be case here, so it's great that you're creating components to the design. However, since the tables haven't gone through styling yet, we decided that we could style the tables at the same time as adding pagination to them. I find it natural to create an actual component in Figma when doing this. So we don't want to "mess with your tickets", just giving a heads up that you don't neet to think about the tables :D

**Comment by AilinMari** [comment]
I fully agree on that! It is indeed a lot that should have been done at sooner that is missing, so it was just hard to get a good view on what actually is being taken care of and not since so many things already was missing. So thanks for the heads up! :D

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Martinekong** [comment]
I am working on issue #102 to create error validation for the contact form so I will also be creating a component out of the error form field and regular form field

**Comment by AilinMari** [comment]
MAde two components for the desktop navbar. One with out the profile and dashboard buttons, and one with them so it's easier to navigate between when you are logged in
