### ISSUE TITLE
Button componants

### ISSUE THREAD

**Issue by kristinatonnessen** [NoroffFEU/edu-gate#75]
- [x]     Primary Button:

        Background: #4CAF50 (primary color)
        Text: White (#FFFFFF)
        Hover: Darker shade of primary (#388E3C)
        Border Radius: 6px
        Padding: 10px 20px
  

- [x]   Secondary Button:

        Outline style with secondary color border (#2196F3) and text
        Hover: Light secondary color background (#BBDEFB)
  

- [x]  Alert Button (for delete actions):

        Background: Accent color (#FF5722)
        Text: White
        Hover: Darker shade of accent color (#E64A19)

**Comment by Anne-Zwift** [comment]
@Foadosman I assumed that the buttons would follow the description of body text but maybe I'm wrong?
Headings: H1 - 32px, H2 - 24px, H3 - 20px
Body Text: 16px for paragraphs, 14px for labels and smaller text.

**Comment by Janicke92** [comment]
Looks perfect! 

Edit: On further inspection I see that the button components do not have the some font size as the buttons in the style guide. And the buttons in the style guide does not have the same font size as described under "Typography" in the style guide. 

Edit 2: I've updated the QA standards with the right font size. Also note that the border for the primary and alert button is not solid.

**Comment by Foadosman** [comment]
Thank you for the feedback! I was a bit confused about the borders and border radius so that really helped.

I have removed the border from the primary buttons and alert buttons.
I have also changed the font to Poppins it is now semibold according to the styleguide.

I also edited the width and height on the buttons because they looked too big.
